# Generated by Django 5.2.17 on 2026-09-03 11:51

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier. Stable for the lifetime of the record.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Business entity name, e.g. 'Customer'. Unique, case-insensitively.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this dataset represents and where it comes from.",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        help_text="Team or person accountable for this dataset, e.g. 'growth-team'.",
                        max_length=150,
                    ),
                ),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Lifecycle stage. Archived datasets are read-only.",
                        max_length=20,
                    ),
                ),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long records of this dataset may be kept, in days. Null means no retention limit has been declared.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "dataset",
                "verbose_name_plural": "datasets",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="dataset_name_unique_ci",
                        violation_error_message="A dataset with this name already exists.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="dataset_name_not_blank",
                        violation_error_message="Dataset name cannot be blank.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "lifecycle_status__in",
                                ["draft", "active", "deprecated", "archived"],
                            )
                        ),
                        name="dataset_lifecycle_status_valid",
                        violation_error_message="Unknown lifecycle status.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("retention_period_days__isnull", True),
                            ("retention_period_days__gt", 0),
                            _connector="OR",
                        ),
                        name="dataset_retention_period_positive",
                        violation_error_message="Retention period must be a positive number of days.",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Public identifier. Stable for the lifetime of the record.",
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Field name, e.g. 'email'. Unique within its dataset, case-insensitively.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "Datetime"),
                            ("uuid", "UUID"),
                            ("json", "JSON"),
                        ],
                        help_text="Logical type of the value this element holds.",
                        max_length=20,
                    ),
                ),
                (
                    "max_length",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum length. Only meaningful for, and only allowed on, string elements.",
                        null=True,
                    ),
                ),
                (
                    "is_nullable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this element may be absent on a record.",
                    ),
                ),
                (
                    "is_primary_key",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this element identifies a record. At most one per dataset.",
                    ),
                ),
                (
                    "is_pii",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this element holds personally identifiable information.",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        help_text="The dataset this element belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_elements",
                        to="catalog.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "data element",
                "verbose_name_plural": "data elements",
                "indexes": [
                    models.Index(
                        fields=["dataset", "is_pii"],
                        name="data_element_dataset_pii_idx",
                    ),
                    models.Index(
                        fields=["data_type"], name="data_element_data_type_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("dataset"),
                        django.db.models.functions.text.Lower("name"),
                        name="data_element_name_unique_per_dataset",
                        violation_error_message="This dataset already has a data element with this name.",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary_key", True)),
                        fields=("dataset",),
                        name="data_element_single_primary_key_per_dataset",
                        violation_error_message="This dataset already has a primary key data element.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="data_element_name_not_blank",
                        violation_error_message="Data element name cannot be blank.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "data_type__in",
                                [
                                    "string",
                                    "integer",
                                    "decimal",
                                    "boolean",
                                    "date",
                                    "datetime",
                                    "uuid",
                                    "json",
                                ],
                            )
                        ),
                        name="data_element_data_type_valid",
                        violation_error_message="Unknown data type.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_length__isnull", True),
                            models.Q(("data_type", "string"), ("max_length__gt", 0)),
                            _connector="OR",
                        ),
                        name="data_element_max_length_only_for_positive_length_strings",
                        violation_error_message="max_length is only allowed on string data elements, and must be positive.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_nullable", True),
                            ("is_primary_key", True),
                            _negated=True,
                        ),
                        name="data_element_primary_key_not_nullable",
                        violation_error_message="A primary key data element cannot be nullable.",
                    ),
                ],
            },
        ),
    ]
